---
## setup defaults for el7
- name: set default redis_version on el7
  set_fact:
    redis_version: 5
  when: (not redis_version) and (ansible_distribution_major_version|int <= 7)

- name: set redis_package_name=redis{{ redis_version }} on el7
  set_fact:
    redis_package_name: "redis{{ redis_version }}"
  when: (redis_version == 5) and (ansible_distribution_major_version|int <= 7)

- name: set redis_package_name=redis{{ redis_version }}u on el7
  set_fact:
    redis_package_name: "redis{{ redis_version }}u"
  when: (not redis_package_name) and (ansible_distribution_major_version|int <= 7)

## setup defaults for el8
- name: set default redis_version on el8
  set_fact:
    redis_version: 5
  when: (not redis_version) and (ansible_distribution_major_version|int >= 8)

- name: set redis_package_name=@redis:{{ redis_version }} on el8
  set_fact:
    redis_package_name: "@redis:{{ redis_version }}"
  when: (not redis_package_name) and (ansible_distribution_major_version|int >= 8)
