- name: install redis
  yum: 
    name: "{{ redis_package_name }}"
    enablerepo: "{{ redis_enablerepo }}"

- name: disable default redis service
  service:
    name: redis
    state: stopped
    enabled: no

- name: create /etc/redis dir
  file:
    path: /etc/redis
    state: directory
    owner: root
    group: root
    mode: 0755
  notify: restart redis

- name: create /var/lib/redis/{{ redis_instance.name }} dir
  file:
    path: /var/lib/redis/{{ redis_instance.name }}
    state: directory
    owner: redis
    group: redis
    mode: 0700

- include_tasks: configure-el{{ ansible_distribution_major_version }}.yml

# append the actual service name to list which the "restart redis" handler iterates
# this is neccessary because handlers cannot use variables in the same way tasks can
- name: register redis-{{ redis_instance.name }} restart
  set_fact: redis_service_restart="{{ redis_service_restart|default([]) }} + [ 'redis-{{ redis_instance.name }}' ]"
  when: redis_config_changed.changed

- name: starting redis-{{ redis_instance.name }} service
  service:
    name: redis-{{ redis_instance.name }}
    state: started
    enabled: yes
